"""
数据处理文件 V2 - 整合K-Means分组与曲线延长
运行一次即可，输出保存到results文件夹

功能：
1. 加载batch1、2、3数据并整合
2. 数据预处理（过滤、插值、平滑）
3. 数据集整体可视化
4. 特征提取与融合式特征筛选
5. K-Means寿命聚类（短/中/长寿命三组）
6. 曲线延长（双指数模型）
7. 分组构建模型输入数据集
8. 长组数据增强
9. 保存分组数据和聚类器

修改说明：
- 短组目标长度固定为1280
- 中组、长组目标长度固定为2560
- 对长组进行数据增强，增加样本数量
"""

import os
import glob
import sys
import json
import pickle
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.lines import Line2D
from scipy.signal import medfilt, savgol_filter
from scipy.interpolate import interp1d, PchipInterpolator
from scipy.ndimage import zoom
from scipy import stats as scipy_stats

# 设置中文字体

# 获取项目根目录
CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(CURRENT_DIR)
DATA_DIR = os.path.join(PROJECT_ROOT, 'data')
OUTPUT_DIR = os.path.join(PROJECT_ROOT, 'results')
PLOT_DATASET_DIR = os.path.join(PROJECT_ROOT, 'plot', 'dataset')

# 导入自定义模块
sys.path.insert(0, CURRENT_DIR)
from battery_feature_extraction import BatteryFeatureExtractor, FusionFeatureSelector
from battery_lifetime_clustering import BatteryLifetimeClustering
from curve_extension_horizontal import SOHCurveExtension, visualize_extension
from plot_style import apply_thesis_plot_style, BATCH_COLORS

# 统一论文绘图风格（中文宋体/英文数字 Times New Roman，10.5pt）
apply_thesis_plot_style()

# Robust console output for Windows terminals with non-UTF8 defaults.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

# 确保输出目录存在
os.makedirs(OUTPUT_DIR, exist_ok=True)
os.makedirs(PLOT_DATASET_DIR, exist_ok=True)

# Keep original fixed 15 handcrafted features for Code2 compatibility.
USE_FIXED_ORIGINAL_15_FEATURES = True
# For main experiments, use the fixed 15 as default to keep setting stable and reproducible.
USE_LIFE_CORR_TOP15_FEATURES = False
USE_SHAPE_SELECTED_FEATURES = False
FIXED_ORIGINAL_15_FEATURES = [
    "energy_efficiency",
    "charge_rate",
    "T_deviation",
    "IR_ewm",
    "QD_curvature",
    "chargetime",
    "chargetime_ma5",
    "IR",
    "IR_ma10",
    "Trange",
    "T_amplitude",
    "chargetime_diff",
    "chargetime_cumsum",
    "Tmin",
    "QD_decay_rate",
]
LIFE_CORR_FEATURE_JSON = os.path.join(
    OUTPUT_DIR, "fixed15_validation", "fixed15_candidate_sets_seed42.json"
)
SHAPE_FEATURE_GLOB = os.path.join(OUTPUT_DIR, "feature_selection_43", "seed*_shape_wrap-*", "final15_features_seed*.csv")
SHAPE_FEATURE_SHORTCUT = os.path.join(OUTPUT_DIR, "final15_features_shape_seed42.csv")


def load_shape_selected_features():
    """Load final15 generated by paper-43 two-stage shape-aware feature selection."""
    candidates = []
    if os.path.exists(SHAPE_FEATURE_SHORTCUT):
        candidates.append(SHAPE_FEATURE_SHORTCUT)
    candidates.extend(glob.glob(SHAPE_FEATURE_GLOB))
    if len(candidates) == 0:
        return []

    candidates = sorted(set(candidates), key=lambda p: os.path.getmtime(p), reverse=True)
    path = candidates[0]
    try:
        df = pd.read_csv(path)
    except Exception as e:
        print(f"[WARN] 读取shape特征失败: {path} ({e})")
        return []

    col = "feature" if "feature" in df.columns else None
    if col is None:
        for c in df.columns:
            if str(c).lower().strip() == "feature":
                col = c
                break
    if col is None:
        return []

    feats = [str(x).strip() for x in df[col].tolist() if str(x).strip()]
    if len(feats) > 0:
        print(f"\n检测到shape-aware两阶段筛选特征文件: {path}")
    return feats


def load_life_corr_top15_features():
    """Load top15 features selected by single-life correlation from fixed15 validation."""
    if not os.path.exists(LIFE_CORR_FEATURE_JSON):
        return []
    try:
        with open(LIFE_CORR_FEATURE_JSON, "r", encoding="utf-8") as f:
            payload = json.load(f)
    except Exception as e:
        print(f"[WARN] 璇诲彇 life-corr 鐗瑰緛鏂囦欢澶辫触: {LIFE_CORR_FEATURE_JSON} ({e})")
        return []

    feats = payload.get("corr_life15", [])
    feats = [str(x).strip() for x in feats if str(x).strip()]
    if len(feats) > 0:
        print(f"\n妫€娴嬪埌鍗曞鍛界浉鍏虫€у墠15鐗瑰緛鏂囦欢: {LIFE_CORR_FEATURE_JSON}")
    return feats

# 全局固定边界
FIXED_BOUNDS = {
    'IR': (0.01, 0.04), 'QC': (0.8, 1.15), 'QD': (0.8, 1.15),
    'Tavg': (30.0, 36.0), 'Tmin': (25.0, 32.0), 'Tmax': (30.0, 42.0),
    'chargetime': (10.0, 200.0), 'cycle': (0.0, 2500.0), 'SOH': (70.0, 105.0),
    'IR_diff': (-0.001, 0.001), 'IR_cumsum': (0.0, 5.0), 'IR_ma10': (0.01, 0.04), 'IR_ewm': (0.01, 0.04),
    'QC_diff': (-0.05, 0.05), 'QD_diff': (-0.05, 0.05), 'QD_decay': (0.0, 0.3),
    'CoulombicEfficiency': (0.9, 1.1), 'Q_diff': (-0.1, 0.3),
    'Tavg_diff': (-2.0, 2.0), 'Trange': (0.0, 15.0), 'T_amplitude': (0.0, 7.5), 'T_deviation': (0.0, 10.0),
    'chargetime_diff': (-20.0, 20.0), 'chargetime_cumsum': (0.0, 1000.0), 
    'chargetime_norm': (0.0, 3.0), 'chargetime_ma5': (10.0, 200.0),
    'charge_rate': (0.005, 0.1), 'energy_efficiency': (0.005, 0.1),
    'QD_decay_rate': (0.0, 0.005), 'QD_curvature': (-0.0001, 0.0001), 'QD_slope': (-0.01, 0.01),
    'IR_growth_rate': (0.0, 0.02), 'Composite_HI': (0.0, 1.0)
}

UNET_NUM_DOWNSAMPLES = 3
UNET_SEQ_MULTIPLE = 2 ** UNET_NUM_DOWNSAMPLES
SEQ_CYCLE_STRIDE = 5


def calculate_eol_metadata(observed_cycles, observed_soh, target_length, threshold=80.0):
    """Estimate EOL from the raw observed trajectory instead of the coarse interpolation grid."""
    observed_cycles = np.asarray(observed_cycles, dtype=float).flatten()
    observed_soh = np.asarray(observed_soh, dtype=float).flatten()

    valid_mask = ~(np.isnan(observed_cycles) | np.isnan(observed_soh))
    observed_cycles = observed_cycles[valid_mask]
    observed_soh = observed_soh[valid_mask]

    if len(observed_cycles) == 0:
        return False, -1.0, 1.0

    sort_idx = np.argsort(observed_cycles)
    observed_cycles = observed_cycles[sort_idx]
    observed_soh = observed_soh[sort_idx]
    observed_cycles, unique_idx = np.unique(observed_cycles, return_index=True)
    observed_soh = observed_soh[unique_idx]

    eol_idx = np.where(observed_soh <= threshold)[0]
    if len(eol_idx) == 0:
        return False, -1.0, 1.0

    first_idx = int(eol_idx[0])
    if first_idx == 0:
        eol_cycle = float(observed_cycles[0])
    else:
        cycle_prev = float(observed_cycles[first_idx - 1])
        cycle_curr = float(observed_cycles[first_idx])
        soh_prev = float(observed_soh[first_idx - 1])
        soh_curr = float(observed_soh[first_idx])

        if abs(soh_curr - soh_prev) < 1e-8:
            eol_cycle = cycle_curr
        else:
            ratio = (threshold - soh_prev) / (soh_curr - soh_prev)
            ratio = float(np.clip(ratio, 0.0, 1.0))
            eol_cycle = cycle_prev + ratio * (cycle_curr - cycle_prev)

    target_cycle = max(float(target_length), 1.0)
    eol_cycle = float(np.clip(eol_cycle, observed_cycles[0], target_cycle))
    return True, eol_cycle, eol_cycle / target_cycle


def augment_battery_data(item, augmentation_factor=2, noise_level=0.02, 
                         scale_range=(0.95, 1.05), time_warp_ratio=0.1):
    """
    对电池数据进行增强，生成多个增强样本
    
    数据增强方法：
    1. 添加高斯噪声
    2. 幅度缩放
    3. 时间扭曲（微小的时间轴变换）
    
    Parameters:
    -----------
    item : dict
        原始电池数据字典
    augmentation_factor : int
        增强倍数，生成多少个增强样本
    noise_level : float
        噪声水平（相对于SOH范围）
    scale_range : tuple
        幅度缩放范围
    time_warp_ratio : float
        时间扭曲比例
        
    Returns:
    --------
    augmented_items : list
        增强后的数据列表
    """
    augmented_items = []
    
    for aug_idx in range(augmentation_factor):
        # 复制原始数据
        aug_item = {
            'battery_id': f"{item['battery_id']}_aug{aug_idx}",
            'source_battery_id': item.get('source_battery_id', item['battery_id']),
            'group_id': item.get('group_id'),
            'group_name': item.get('group_name'),
            'cycle_life': item['cycle_life'],
            'target_length': item['target_length'],
            'seq_length': item['seq_length'],
            'observed_seq_length': item.get('observed_seq_length'),
            'observed_max_cycle': item.get('observed_max_cycle'),
            'eol_exists': item.get('eol_exists', False),
            'eol_cycle': item.get('eol_cycle', -1.0),
            'eol_fraction': item.get('eol_fraction', 1.0),
            'extension_info': item['extension_info'].copy(),
        }
        
        # 1. SOH张量增强
        soh_tensor = item['soh_tensor'].copy()
        
        # 添加微小高斯噪声
        noise = np.random.normal(0, noise_level * 0.1, soh_tensor.shape)
        soh_aug = soh_tensor + noise.astype(np.float32)
        
        # 幅度缩放
        scale = np.random.uniform(scale_range[0], scale_range[1])
        soh_aug = soh_aug * scale
        
        # 确保范围在[-1, 1]之间
        soh_aug = np.clip(soh_aug, -1.0, 1.0).astype(np.float32)
        aug_item['soh_tensor'] = soh_aug
        
        # 2. 特征矩阵增强
        feat_matrix = item['feature_matrix'].copy()
        
        # 对特征矩阵添加微小噪声
        feat_noise = np.random.normal(0, noise_level * 0.05, feat_matrix.shape)
        feat_aug = feat_matrix + feat_noise.astype(np.float32)
        feat_aug = np.clip(feat_aug, -1.0, 1.0).astype(np.float32)
        aug_item['feature_matrix'] = feat_aug
        
        # 3. 损失掩码保持不变
        aug_item['loss_mask'] = item['loss_mask'].copy()
        
        # 4. 原始数据增强（用于可视化）
        raw_soh = item['raw_soh'].copy()
        raw_noise = np.random.normal(0, noise_level * 2, raw_soh.shape)
        raw_soh_aug = raw_soh + raw_noise
        raw_soh_aug = np.clip(raw_soh_aug, 60, 105)
        aug_item['raw_soh'] = raw_soh_aug
        aug_item['raw_cycles'] = item['raw_cycles'].copy()
        
        # 标记为增强数据
        aug_item['is_augmented'] = True
        aug_item['augmentation_idx'] = aug_idx
        
        augmented_items.append(aug_item)
    
    return augmented_items


def load_batch_data():
    """加载batch1、2、3数据"""
    print("=" * 60)
    print("【步骤1】加载原始数据")
    print("=" * 60)
    
    batch1_path = os.path.join(DATA_DIR, 'batch1.pkl')
    batch2_path = os.path.join(DATA_DIR, 'batch2.pkl')
    batch3_path = os.path.join(DATA_DIR, 'batch3.pkl')
    
    for path in [batch1_path, batch2_path, batch3_path]:
        if not os.path.exists(path):
            raise FileNotFoundError(f"数据文件不存在: {path}")
    
    batch1 = pickle.load(open(batch1_path, 'rb'))
    batch2 = pickle.load(open(batch2_path, 'rb'))
    batch3 = pickle.load(open(batch3_path, 'rb'))
    
    print(f"Batch1: {len(batch1)} 个电池")
    print(f"Batch2: {len(batch2)} 个电池")
    print(f"Batch3: {len(batch3)} 个电池")
    
    return batch1, batch2, batch3


def _extract_raw_soh(summary_dict, nominal_capacity=1.1):
    """从原始 summary 中提取 cycle-SOH，用于原始数据集可视化。"""
    cycles = np.asarray(summary_dict.get("cycle", []), dtype=np.float64).flatten()
    qd = np.asarray(summary_dict.get("QD", []), dtype=np.float64).flatten()
    n = min(len(cycles), len(qd))
    if n < 5:
        return None, None

    cycles = cycles[:n]
    soh = (qd[:n] / nominal_capacity) * 100.0
    valid = np.isfinite(cycles) & np.isfinite(soh) & (soh >= 60.0) & (soh <= 110.0)
    if np.sum(valid) < 5:
        return None, None

    cycles = cycles[valid]
    soh = soh[valid]
    sort_idx = np.argsort(cycles)
    return cycles[sort_idx], soh[sort_idx]


def visualize_raw_batches(batch1, batch2, batch3):
    """绘制原始数据集图：batch1/2/3 三色区分。"""
    print("\n" + "=" * 60)
    print("【步骤】原始数据集可视化（按 batch 分色）")
    print("=" * 60)

    fig, ax = plt.subplots(figsize=(12, 6))
    batch_map = [(1, batch1), (2, batch2), (3, batch3)]
    valid_counts = {1: 0, 2: 0, 3: 0}

    for batch_id, batch_dict in batch_map:
        color = BATCH_COLORS[batch_id]
        for _, batt in batch_dict.items():
            summary = batt.get("summary", {})
            cycles, soh = _extract_raw_soh(summary)
            if cycles is None:
                continue
            valid_counts[batch_id] += 1
            ax.plot(cycles, soh, color=color, alpha=0.35, linewidth=0.9)

    legend_handles = [
        Line2D([0], [0], color=BATCH_COLORS[1], lw=2.2, label=f"batch1（n={valid_counts[1]}）"),
        Line2D([0], [0], color=BATCH_COLORS[2], lw=2.2, label=f"batch2（n={valid_counts[2]}）"),
        Line2D([0], [0], color=BATCH_COLORS[3], lw=2.2, label=f"batch3（n={valid_counts[3]}）"),
    ]
    ax.legend(handles=legend_handles, loc="best")
    ax.set_xlabel("循环次数")
    ax.set_ylabel("SOH (%)")
    ax.set_title("原始数据集 SOH 曲线（按 batch1/2/3 分色）")
    ax.set_ylim(70, 105)
    ax.grid(True, linestyle="--", alpha=0.35)

    plt.tight_layout()
    save_path = os.path.join(PLOT_DATASET_DIR, "0_raw_dataset_batches_colored.png")
    plt.savefig(save_path, dpi=300, bbox_inches="tight")
    plt.close()
    print(f"✓ 原始数据集分色图已保存: {save_path}")


def merge_and_preprocess_data(batch1, batch2, batch3):
    """整合与预处理数据"""
    print("\n" + "=" * 60)
    print("【步骤2】数据整合与预处理")
    print("=" * 60)
    
    # 剔除Batch1中的坏点
    bad_keys_b1 = ['b1c8', 'b1c10', 'b1c12', 'b1c13', 'b1c22']
    for bk in bad_keys_b1:
        if bk in batch1:
            del batch1[bk]
    
    # Batch1和Batch2拼接
    batch2_keys = ['b2c7', 'b2c8', 'b2c9', 'b2c15', 'b2c16']
    batch1_keys = ['b1c0', 'b1c1', 'b1c2', 'b1c3', 'b1c4']
    add_len = [662, 981, 1060, 208, 482]
    
    for i, bk in enumerate(batch1_keys):
        if bk in batch1:
            batch1[bk]['cycle_life'] = batch1[bk]['cycle_life'] + add_len[i]
            for j in batch1[bk]['summary'].keys():
                if j == 'cycle':
                    batch1[bk]['summary'][j] = np.hstack((
                        batch1[bk]['summary'][j],
                        batch2[batch2_keys[i]]['summary'][j] + len(batch1[bk]['summary'][j])
                    ))
                else:
                    batch1[bk]['summary'][j] = np.hstack((
                        batch1[bk]['summary'][j],
                        batch2[batch2_keys[i]]['summary'][j]
                    ))
            last_cycle = len(batch1[bk]['cycles'].keys())
            for j, jk in enumerate(batch2[batch2_keys[i]]['cycles'].keys()):
                batch1[bk]['cycles'][str(last_cycle + j)] = batch2[batch2_keys[i]]['cycles'][jk]
    
    for bk in batch2_keys:
        if bk in batch2:
            del batch2[bk]
    
    # 剔除Batch3中的坏点
    bad_keys_b3 = ['b3c37', 'b3c2', 'b3c23', 'b3c32', 'b3c42', 'b3c43']
    for bk in bad_keys_b3:
        if bk in batch3:
            del batch3[bk]
    
    # 合并所有数据
    bat_dict = {**batch1, **batch2, **batch3}
    print(f"合并后总电池数: {len(bat_dict)}")
    
    # 数据清洗
    print("\n开始数据清洗...")
    cleaned_bat_dict = {}
    NOMINAL_CAPACITY = 1.1
    
    for key in bat_dict.keys():
        summary = bat_dict[key]['summary']
        
        if 'QD' not in summary or 'cycle' not in summary:
            continue
        
        cycles = np.array(summary['cycle'])
        capacity = np.array(summary['QD'])
        
        capacity_clean = capacity.copy()
        capacity_clean[capacity_clean > 1.3] = np.nan
        capacity_clean[capacity_clean < 0.1] = np.nan
        
        if np.isnan(capacity_clean).any():
            valid_mask = ~np.isnan(capacity_clean)
            if np.sum(valid_mask) < 10:
                continue
            f = interp1d(cycles[valid_mask], capacity_clean[valid_mask],
                        kind='linear', fill_value="extrapolate")
            capacity_filled = f(cycles)
        else:
            capacity_filled = capacity_clean
        
        capacity_med = medfilt(capacity_filled, kernel_size=5)
        window_len = min(51, len(capacity_med) // 2 * 2 + 1)
        if window_len < 3:
            continue
        capacity_smoothed = savgol_filter(capacity_med, window_length=window_len, polyorder=2)
        
        soh = (capacity_smoothed / NOMINAL_CAPACITY) * 100.0
        
        cleaned_bat_dict[key] = bat_dict[key].copy()
        cleaned_bat_dict[key]['summary']['QD'] = capacity_smoothed
        cleaned_bat_dict[key]['summary']['SOH'] = soh
        cleaned_bat_dict[key]['summary']['SOH_processed'] = soh
    
    print(f"清洗后有效电池数: {len(cleaned_bat_dict)}")
    
    return cleaned_bat_dict


def visualize_dataset(bat_dict):
    """数据集整体可视化"""
    print("\n" + "=" * 60)
    print("【步骤3】数据集可视化")
    print("=" * 60)
    
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    
    ax1 = axes[0]
    for key in bat_dict.keys():
        cycles = bat_dict[key]['summary']['cycle']
        soh = bat_dict[key]['summary']['SOH']
        ax1.plot(cycles, soh, alpha=0.6, linewidth=0.8)
    
    ax1.set_xlabel('循环次数', fontsize=12)
    ax1.set_ylabel('SOH (%)', fontsize=12)
    ax1.set_title(f'所有电池SOH曲线 (共{len(bat_dict)}个)', fontsize=14)
    ax1.grid(True, linestyle='--', alpha=0.5)
    ax1.set_ylim(70, 105)
    
    ax2 = axes[1]
    cycle_lives = []
    for key in bat_dict.keys():
        cycle_life = int(bat_dict[key]['cycle_life'][0][0])
        cycle_lives.append(cycle_life)
    
    ax2.hist(cycle_lives, bins=30, color='steelblue', edgecolor='white', alpha=0.8)
    ax2.axvline(np.mean(cycle_lives), color='red', linestyle='--', 
                label=f'平均值: {np.mean(cycle_lives):.0f}')
    ax2.set_xlabel('循环寿命', fontsize=12)
    ax2.set_ylabel('电池数量', fontsize=12)
    ax2.set_title('电池循环寿命分布', fontsize=14)
    ax2.legend(fontsize=10)
    ax2.grid(True, linestyle='--', alpha=0.5)
    
    plt.tight_layout()
    save_path = os.path.join(PLOT_DATASET_DIR, '1_dataset_overview.png')
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"✓ 数据集概览图已保存: {save_path}")
    
    return cycle_lives


def extract_and_select_features(bat_dict, n_cycles=100):
    """特征提取与融合式特征筛选"""
    print("\n" + "=" * 60)
    print("【步骤4】特征提取与融合式特征筛选")
    print("=" * 60)
    
    sample_battery = list(bat_dict.values())[0]
    sample_extractor = BatteryFeatureExtractor(sample_battery)
    sample_features_df = sample_extractor.extract_all_features()
    exclude_cols = ['SOH', 'cycle', 'battery_id']
    original_feature_names = [col for col in sample_features_df.columns if col not in exclude_cols]
    
    print(f"原始特征数量: {len(original_feature_names)}")
    
    battery_features = []
    
    for key, battery_data in bat_dict.items():
        try:
            extractor = BatteryFeatureExtractor(battery_data)
            features_df = extractor.extract_all_features()
            
            features_df = features_df[features_df['cycle'] <= n_cycles].copy()
            
            if len(features_df) < 10:
                continue
            
            stats = {'battery_id': key}
            
            for col in original_feature_names:
                if col not in features_df.columns:
                    continue
                values = features_df[col].values
                stats[f'{col}_mean'] = np.mean(values)
                stats[f'{col}_std'] = np.std(values)
                stats[f'{col}_min'] = np.min(values)
                stats[f'{col}_max'] = np.max(values)
                stats[f'{col}_slope'] = np.polyfit(np.arange(len(values)), values, 1)[0] if len(values) > 1 else 0
                stats[f'{col}_first'] = values[0]
                stats[f'{col}_last'] = values[-1] if len(values) > 0 else values[0]
                stats[f'{col}_delta'] = stats[f'{col}_last'] - stats[f'{col}_first']
                if stats[f'{col}_first'] != 0:
                    stats[f'{col}_rate'] = stats[f'{col}_delta'] / abs(stats[f'{col}_first'])
                else:
                    stats[f'{col}_rate'] = 0
            
            stats['cycle_life'] = int(battery_data['cycle_life'][0][0])
            battery_features.append(stats)
            
        except Exception as e:
            print(f"  {key}: 特征提取失败 - {e}")
    
    if len(battery_features) == 0:
        raise ValueError("没有成功提取到任何电池特征")
    
    features_df = pd.DataFrame(battery_features)
    features_df = features_df.dropna()
    
    print(f"处理电池数: {len(features_df)}")
    
    exclude_cols = ['battery_id', 'cycle_life']
    stat_feature_cols = [col for col in features_df.columns if col not in exclude_cols]
    X = features_df[stat_feature_cols]
    y = features_df['cycle_life']
    
    print(f"\n特征验证方式: 电池级别")
    print(f"  - 使用前{n_cycles}循环的特征统计量")
    print(f"  - 预测目标: 循环寿命")
    print(f"  - 样本数: {len(y)} 个电池")
    print(f"  - 统计量特征数: {len(stat_feature_cols)}")
    
    correlations = {}
    for col in stat_feature_cols:
        corr, _ = scipy_stats.pearsonr(X[col].values, y)
        if np.isnan(corr):
            corr = 0
        correlations[col] = abs(corr)
    
    sorted_corr = sorted(correlations.items(), key=lambda x: x[1], reverse=True)
    max_corr = sorted_corr[0][1] if sorted_corr else 0
    
    print(f"\n相关系数分析:")
    print(f"  最高相关系数: {max_corr:.4f}")
    
    print(f"\n前15个统计量特征相关系数:")
    for name, corr in sorted_corr[:15]:
        print(f"    {name}: {corr:.4f}")
    
    # 使用融合式特征选择器（内部会根据相关系数水平自动调整策略）
    selector = FusionFeatureSelector(
        min_features=5, 
        random_state=42,
        estimator='mlp'
    )
    X_selected = selector.fit_transform(X, y, verbose=True)
    
    # 使用selector提供的正确识别的原始特征名
    selected_original_features = selector.selected_original_features
    
    return features_df, selector, selected_original_features, original_feature_names


def perform_clustering(bat_dict, output_dir):
    """
    执行K-Means寿命聚类（论文方法）
    
    使用论文中的特征：var_△Q100-10 和 peak_△Q100-10
    这两个特征与电池寿命高度相关（ρ ≈ -0.93）
    """
    print("\n" + "=" * 60)
    print("【步骤5】K-Means寿命聚类（论文方法）")
    print("=" * 60)
    
    clustering = BatteryLifetimeClustering(n_clusters=3, random_state=42)
    
    # 提取论文中的特征
    print("\n提取论文中的寿命预测特征...")
    print("  - var_△Q100-10: 第100循环与第10循环放电容量差的方差")
    print("  - peak_△Q100-10: |△Q100-10(V)| 的峰值")
    
    lifetime_features = clustering.extract_lifetime_features(bat_dict)
    print(f"\n成功提取特征的电池数: {len(lifetime_features)}")
    
    # 聚类
    clustering.fit(lifetime_features, output_dir=output_dir)
    
    return clustering, lifetime_features


def build_grouped_dataset(bat_dict, clustering, selected_features, 
                          n_cycles=100, matrix_size=100):
    """
    分组构建模型输入数据集
    
    为每个寿命组确定目标步数，并进行曲线延长
    """
    print("\n" + "=" * 60)
    print("【步骤6】分组构建模型数据集")
    print("=" * 60)
    
    group_names = ['short', 'medium', 'long']
    grouped_data = {i: {'name': group_names[i], 'data': [], 'target_length': 0} for i in range(3)}
    
    # 确定每组的目标长度
    for cluster_id in range(3):
        target_length = clustering.get_target_seq_length(cluster_id)
        grouped_data[cluster_id]['target_length'] = target_length
        print(f"\n{group_names[cluster_id]}寿命组目标长度: {target_length}")
    
    # 处理每个电池
    extender = SOHCurveExtension(min_soh=None, max_extension_ratio=0.5, soh_bounds=(0.0, 100.0))
    battery_to_cluster = {}
    
    # 构建battery_id到cluster的映射
    for cluster_id in range(3):
        for bid in clustering.cluster_info['groups'][cluster_id]['battery_ids']:
            battery_to_cluster[bid] = cluster_id
    
    print("\n处理各电池数据...")
    
    for key, battery_data in bat_dict.items():
        if key not in battery_to_cluster:
            continue
        
        cluster_id = battery_to_cluster[key]
        target_length = grouped_data[cluster_id]['target_length']
        
        summary = battery_data['summary']
        
        if 'SOH_processed' not in summary or 'cycle' not in summary:
            continue
        
        soh = np.array(summary['SOH_processed'])
        cycles = np.array(summary['cycle'])
        cycle_life = int(battery_data['cycle_life'][0][0])
        
        # 曲线延长
        try:
            extended_cycles, extended_soh, ext_info = extender.extend_soh_curve(
                cycles, soh, target_length, verbose=False
            )
        except Exception as e:
            print(f"  {key}: 曲线延长失败 - {e}")
            continue
        
        # 插值到固定长度
        seq_length = target_length // SEQ_CYCLE_STRIDE
        if seq_length % UNET_SEQ_MULTIPLE != 0:
            raise ValueError(
                f"{key} 的 seq_length={seq_length} 不满足 U-Net 长度要求，"
                f"必须能被 {UNET_SEQ_MULTIPLE} 整除。当前 target_length={target_length}。"
            )
        cycle_grid = np.linspace(target_length / seq_length, target_length, seq_length)

        try:
            f_interp = PchipInterpolator(extended_cycles, extended_soh, extrapolate=True)
            soh_interp = f_interp(cycle_grid)
        except Exception:
            f_interp = interp1d(
                extended_cycles,
                extended_soh,
                kind='linear',
                bounds_error=False,
                fill_value=(extended_soh[0], extended_soh[-1]),
            )
            soh_interp = f_interp(cycle_grid)
        soh_interp = np.minimum.accumulate(np.asarray(soh_interp, dtype=np.float32))
        
        # SOH归一化到[-1, 1]
        soh_norm = (soh_interp / 100.0) * 2.0 - 1.0
        
        # 提取特征
        features = []
        for feat_name in selected_features:
            if feat_name in summary:
                feat = np.array(summary[feat_name]).flatten()[:n_cycles]
                
                b_min, b_max = FIXED_BOUNDS.get(feat_name, (None, None))
                if b_min is None:
                    b_min, b_max = np.percentile(feat, [5, 95])
                    if b_max <= b_min:
                        b_max = b_min + 1e-6
                
                feat = np.clip(feat, b_min, b_max)
                feat = (feat - b_min) / (b_max - b_min) * 2.0 - 1.0
                
                if len(feat) < n_cycles:
                    feat = np.pad(feat, (0, n_cycles - len(feat)), 'constant')
            else:
                feat = np.zeros(n_cycles)
            
            features.append(feat)
        
        feat_array = np.vstack(features)
        
        # 插值为 matrix_size × matrix_size 矩阵
        feature_matrix = feat_array.astype(np.float32)
        # 【新增】计算损失掩码 (Loss Mask)，标识真实数据部分
        observed_max_cycle = int(ext_info.get('original_max_cycle', int(cycles[-1])))
        true_seq_len = int(np.searchsorted(cycle_grid, observed_max_cycle, side='right'))
        true_seq_len = max(1, min(seq_length, true_seq_len))
        observed_raw_mask = np.asarray(cycles, dtype=float) <= float(observed_max_cycle)
        observed_raw_cycles = np.asarray(cycles, dtype=np.float32)[observed_raw_mask]
        observed_raw_soh = np.asarray(soh, dtype=np.float32)[observed_raw_mask]
        eol_exists, eol_cycle, eol_fraction = calculate_eol_metadata(
            np.asarray(cycles, dtype=float)[observed_raw_mask],
            np.asarray(soh, dtype=float)[observed_raw_mask],
            target_length,
            threshold=80.0,
        )
        loss_mask = np.zeros(seq_length, dtype=np.float32)
        loss_mask[:true_seq_len] = 1.0 # 真实数据对应位置为1，外推数据位置为0

        grouped_data[cluster_id]['data'].append({
            'battery_id': key,
            'source_battery_id': key,
            'group_id': cluster_id,
            'group_name': group_names[cluster_id],
            'soh_tensor': soh_norm.astype(np.float32),
            'feature_matrix': feature_matrix, # 直接存 raw 特征
            'loss_mask': loss_mask,           # 存入掩码
            'cycle_life': cycle_life,
            'raw_soh': extended_soh,
            'raw_cycles': extended_cycles,
            'observed_raw_soh': observed_raw_soh,
            'observed_raw_cycles': observed_raw_cycles,
            'extension_info': ext_info,
            'observed_seq_length': true_seq_len,
            'observed_max_cycle': observed_max_cycle,
            'eol_exists': bool(eol_exists),
            'eol_cycle': float(eol_cycle),
            'eol_fraction': float(eol_fraction),
            'target_length': target_length,
            'seq_length': seq_length
        })
    
    # 【新增】对长组进行数据增强
    print("\n【数据增强】对长寿命组进行数据增强...")
    long_group_id = 2  # 长寿命运对应 cluster_id = 2
    augmentation_factor = 3  # 每个样本生成3个增强样本
    
    if long_group_id in grouped_data and len(grouped_data[long_group_id]['data']) > 0:
        original_long_samples = grouped_data[long_group_id]['data'].copy()
        augmented_count = 0
        
        for item in original_long_samples:
            # 生成增强样本
            aug_items = augment_battery_data(
                item, 
                augmentation_factor=augmentation_factor,
                noise_level=0.015,
                scale_range=(0.97, 1.03)
            )
            grouped_data[long_group_id]['data'].extend(aug_items)
            augmented_count += len(aug_items)
        
        print(f"  长寿命组原始样本数: {len(original_long_samples)}")
        print(f"  长寿命组增强后样本数: {len(grouped_data[long_group_id]['data'])}")
        print(f"  新增增强样本数: {augmented_count}")
    
    # 输出统计
    print("\n分组数据统计:")
    for cluster_id in range(3):
        n_samples = len(grouped_data[cluster_id]['data'])
        target_length = grouped_data[cluster_id]['target_length']
        # 统计原始和增强样本
        n_original = sum(1 for d in grouped_data[cluster_id]['data'] if not d.get('is_augmented', False))
        n_augmented = sum(1 for d in grouped_data[cluster_id]['data'] if d.get('is_augmented', False))
        n_eol_positive = sum(1 for d in grouped_data[cluster_id]['data'] if bool(d.get('eol_exists', False)))
        if n_augmented > 0:
            print(
                f"  {group_names[cluster_id]}寿命组: {n_samples} 个样本 "
                f"(原始: {n_original}, 增强: {n_augmented}, EOL正样本: {n_eol_positive}), "
                f"目标长度: {target_length}"
            )
        else:
            print(
                f"  {group_names[cluster_id]}寿命组: {n_samples} 个样本 "
                f"(EOL正样本: {n_eol_positive}), 目标长度: {target_length}"
            )
    
    return grouped_data


def visualize_grouped_data(grouped_data, output_dir):
    """可视化分组数据：仅输出同轴叠加版。"""
    print("\n" + "=" * 60)
    print("【步骤7】分组数据可视化")
    print("=" * 60)
    
    group_names = ['短寿命组', '中寿命组', '长寿命组']
    # 比当前浅色更深一档，但仍浅于聚类中心色
    colors = ['#89B0D0', '#A9D4C8', '#F8CF8D']

    def _plot_group_curves(ax, data_list, color):
        for item in data_list:
            cycles = item['raw_cycles']
            soh = item['raw_soh']
            ext_info = item['extension_info']

            if ext_info.get('extended', False):
                orig_len = ext_info.get('original_length')
                if orig_len is None:
                    idx = np.where(cycles >= item['cycle_life'])[0]
                    orig_len = idx[0] if len(idx) > 0 else len(cycles)

                ax.plot(
                    cycles[:orig_len],
                    soh[:orig_len],
                    color=color,
                    alpha=0.95,
                    linewidth=1.35,
                )

                if orig_len < len(cycles):
                    start_idx = max(orig_len - 1, 0)
                    ax.plot(
                        cycles[start_idx:],
                        soh[start_idx:],
                        color=color,
                        alpha=0.9,
                        linewidth=1.3,
                        linestyle='--',
                    )
            else:
                ax.plot(
                    cycles,
                    soh,
                    color=color,
                    alpha=0.95,
                    linewidth=1.35,
                )

    fig2, ax2 = plt.subplots(figsize=(15.0 / 2.54, 6.8 / 2.54))

    for cluster_id in range(3):
        data_list = grouped_data[cluster_id]['data']
        _plot_group_curves(ax2, data_list, colors[cluster_id])

    legend_handles = [
        Line2D([0], [0], color=colors[0], lw=2.6, label=group_names[0]),
        Line2D([0], [0], color=colors[1], lw=2.6, label=group_names[1]),
        Line2D([0], [0], color=colors[2], lw=2.6, label=group_names[2]),
    ]
    ax2.legend(handles=legend_handles, loc='lower left', frameon=True)

    y_min, y_max = 60, 105
    ax2.set_ylim(y_min, y_max)

    target_lengths = [int(grouped_data[i]['target_length']) for i in range(3)]
    y_tops = [78.0, 80.0, 82.0]
    text_y = y_min + 1.2
    label_dx = 22.0
    for i, t_len in enumerate(target_lengths):
        ax2.plot(
            [t_len, t_len],
            [text_y + 0.2, y_tops[i]],
            color=colors[i],
            linestyle='--',
            linewidth=1.4,
            alpha=1.0,
            zorder=6,
        )
        ax2.text(
            t_len - label_dx,
            text_y,
            f'{t_len}',
            color=colors[i],
            ha='right',
            va='bottom',
            fontsize=10.5,
        )

    x_max = max(np.max(item['raw_cycles']) for cid in range(3) for item in grouped_data[cid]['data'])
    ax2.set_xlim(-120, x_max + 120)
    ax2.set_xlabel('循环次数')
    ax2.set_ylabel(r'$\mathit{SOH}$ / %')
    ax2.grid(True, linestyle='--', alpha=0.35)

    plt.tight_layout()
    save_path_overlay = os.path.join(output_dir, 'grouped_data_overview_overlay.png')
    plt.savefig(save_path_overlay, dpi=300)
    plt.close(fig2)
    print(f"✓ 分组曲线同轴叠加图已保存: {save_path_overlay}")


def main():
    """主函数"""
    print("=" * 60)
    print("电池数据处理流程 V2")
    print("整合K-Means分组与曲线延长")
    print("=" * 60)
    print(f"数据目录: {DATA_DIR}")
    print(f"输出目录: {OUTPUT_DIR}")
    print()
    
    # 1. 加载数据
    batch1, batch2, batch3 = load_batch_data()
    visualize_raw_batches(batch1, batch2, batch3)

    # 2. 整合与预处理
    bat_dict = merge_and_preprocess_data(batch1, batch2, batch3)
    
    # 3. 数据集可视化
    cycle_lives = visualize_dataset(bat_dict)
    
    # 4. 特征提取与筛选
    features_df, selector, selected_features, original_feature_names = extract_and_select_features(bat_dict)

    # Prefer shape-aware final15 (paper-43 two-stage), fallback to fixed original 15.
    if USE_FIXED_ORIGINAL_15_FEATURES:
        preferred = []
        if USE_SHAPE_SELECTED_FEATURES:
            preferred = load_shape_selected_features()
            preferred = [f for f in preferred if f in original_feature_names]
            if len(preferred) >= 10:
                selected_features = preferred
                print("\n使用 shape-aware 两阶段筛选 final15 特征:")
                for feat in selected_features:
                    print(f"  - {feat}")
            elif len(preferred) > 0:
                print(f"\n[WARN] shape-aware final15 可用特征不足(仅{len(preferred)}个)，回退固定15特征。")

        if len(preferred) < 10:
            available = []
            missing = []
            if USE_LIFE_CORR_TOP15_FEATURES:
                life_corr = load_life_corr_top15_features()
                life_corr = [f for f in life_corr if f in original_feature_names]
                if len(life_corr) >= 10:
                    selected_features = life_corr
                    print("\n浣跨敤鍗曞鍛界浉鍏虫€у墠15鐗瑰緛锛圕orr-life Top15锛?:")
                    for feat in selected_features:
                        print(f"  - {feat}")
                elif len(life_corr) > 0:
                    print(f"\n[WARN] life-corr Top15 可用特征不足(仅{len(life_corr)}个)，回退固定15。")

            if True:
                available = [f for f in FIXED_ORIGINAL_15_FEATURES if f in original_feature_names]
                missing = [f for f in FIXED_ORIGINAL_15_FEATURES if f not in original_feature_names]
            if len(available) >= 10:
                selected_features = available
                print("\n使用固定原始15特征（Code2主流程）:")
                for feat in selected_features:
                    print(f"  - {feat}")
                if missing:
                    print(f"  [WARN] 缺失特征已跳过: {missing}")
            else:
                print(
                    "\n[WARN] 固定原始15特征在当前数据中可用数量不足，"
                    f"available={len(available)}, missing={missing}"
                )
                print("      回退为融合式特征筛选结果，避免流程中断。")
    
    # 5. K-Means聚类（论文方法）
    clustering, lifetime_features = perform_clustering(bat_dict, PLOT_DATASET_DIR)
    
    # 6. 分组构建数据集
    grouped_data = build_grouped_dataset(bat_dict, clustering, selected_features)
    
    # 7. 分组数据可视化
    visualize_grouped_data(grouped_data, PLOT_DATASET_DIR)
    
    # 8. 保存结果
    all_data = []
    for cluster_id in range(3):
        all_data.extend(grouped_data[cluster_id]['data'])

    max_target_length = max(grouped_data[cluster_id]['target_length'] for cluster_id in range(3))
    max_seq_length = max_target_length // SEQ_CYCLE_STRIDE

    result = {
        'grouped_data': grouped_data,
        'all_data': all_data,
        'selected_features': selected_features,
        'correlation_scores': selector.correlation_scores,
        'clustering_info': clustering.cluster_info,
        'n_cycles': 100,
        'n_groups': 3,
        'max_target_length': max_target_length,
        'max_seq_length': max_seq_length,
        'cycle_stride': SEQ_CYCLE_STRIDE,
    }
    
    # 保存分组数据
    output_path = os.path.join(OUTPUT_DIR, 'grouped_data.pkl')
    with open(output_path, 'wb') as f:
        pickle.dump(result, f)
    
    # 保存聚类器
    clustering_path = os.path.join(OUTPUT_DIR, 'clustering_model.pkl')
    clustering.save(clustering_path)  # 调用我们在 clustering 类中写好的 save 方法
    
    print("\n" + "=" * 60)
    print("数据处理完成")
    print("=" * 60)
    print(f"✓ 分组数据已保存: {output_path}")
    print(f"✓ 聚类器已保存: {os.path.join(OUTPUT_DIR, 'clustering_model.pkl')}")
    print(f"✓ 可视化结果保存至: {OUTPUT_DIR}")
    
    # 输出各组统计
    print("\n分组统计:")
    for cluster_id in range(3):
        n_samples = len(grouped_data[cluster_id]['data'])
        target_length = grouped_data[cluster_id]['target_length']
        if n_samples > 0:
            lifetimes = [d['cycle_life'] for d in grouped_data[cluster_id]['data']]
            print(f"  组{cluster_id}: {n_samples}个电池, 寿命范围 {min(lifetimes)}-{max(lifetimes)}, 目标长度 {target_length}")
    
    return result


if __name__ == "__main__":
    result = main()
